### ISSUE TITLE
User should be able to see list of search results on matches page

### ISSUE THREAD

**Issue by lauratheriot** [lovely-javascript-people/BiblioBarter#87]

**Comment by lauratheriot** [comment]
make list on matches component *ngFor --> use let

**Comment by lauratheriot** [comment]
List with sample data is currently rendering

**Comment by lauratheriot** [comment]
listings prop in home.page.ts (currently sample data) should be set to array of listings returned from search query

**Comment by pnguyen89** [comment]
search results return an array of objects. Each object holds information about book, then a property to object listing
